add defineAsyncComponent API
vuejs/composition-api pull request #644
Opened 2021-02-10 21:54 UTC by mathe42

This PR adds a implementation for defineAsyncComponent (I used code from the vue3 implementation) and returns a function async component as used in vue2 (see docs link). This should be a quite similar implementation as vue3 uses and should be compatible in most cases.

Some notes:
1. This adds no test (when PR looks good and I have time I would add them but not before march.)
2. Not shure of the typing of `Component` used `VueProxy<any,any>` but maybe there are better options
3. Changed option suspensible  as vue2 has no suspense component
3. Helpfull docs:
* https://vuejs.org/v2/guide/components-dynamic-async.html#Handling-Loading-State
* https://v3.vuejs.org/api/global-api.html#defineasynccomponent

2021-02-11 11:04 UTC, mathe42 commented on src/component/defineAsyncComponent.ts
> +      component: component as any, // there is a type missmatch between vue2 type and the docs
Types of Vue2 are not correct in that place I created a PR for that https://github.com/vuejs/vue/pull/11906

2021-02-12 15:56 UTC, antfu requested changes
Can you add some runtime tests as well? Thanks.

2021-02-12 18:08 UTC, mathe42 commented
Will work in it.

Should be easy with the test from vue3 https://github.com/vuejs/vue-next/blob/master/packages/runtime-core/__tests__/apiAsyncComponent.spec.ts ...

2021-02-13 15:01 UTC, mathe42 commented
Added tests.

Following things are not like vue3:

1. On timeout a Error is displayed.
2. Error component access to thrown Error is not the same.
3. Resolve after timeout doesn't show the component.

2021-02-18 03:29 UTC, merged

2021-02-18 06:09 UTC, mathe42 commented
Thanks👍