fix(watch): watched previous values can't be destructure on first fire.
vuejs/composition-api pull request #727
Opened 2021-06-08 07:26 UTC by ygj6

Fix: #418, align behavior with vue-next.

2021-06-08 08:16 UTC, posva requested changes
Nice!

2021-06-08 08:16 UTC, posva commented on src/apis/watch.ts
>        applyCb(n, o)
I think it's better not to modify the argument
```suggestion
      // o is undefined on the first call
      applyCb(n, isArray(n) ? [] : o)
```

2021-06-08 13:07 UTC, posva approved these changes

2021-06-17 09:26 UTC, pikax approved these changes
Thank you

2021-06-17 19:30 UTC, merged